version: '3'
services:

  # Redis DB
  db:
    container_name: eyesuite_redis
    image: redis:latest
    volumes:
      - data:/data
    restart: always

  # OCR server
  server:
    container_name: eyesuite
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: always

volumes:
  data: